# Generated by Django 4.0.4 on 2022-05-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reddit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('link', models.URLField()),
                ('thumbnail', models.URLField()),
                ('user_name', models.CharField(max_length=200)),
                ('guid', models.CharField(max_length=50)),
            ],
        ),
    ]
